services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: run-finder-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: runfinder
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
